# Generated by Django 4.0 on 2023-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se_function', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '員工', 'verbose_name_plural': '員工'},
        ),
        migrations.AlterModelOptions(
            name='employeesalestarget',
            options={'verbose_name': '員工業績目標', 'verbose_name_plural': '員工業績目標'},
        ),
        migrations.AlterModelOptions(
            name='employeeservicereview',
            options={'verbose_name': '服務評價', 'verbose_name_plural': '服務評價'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '會員', 'verbose_name_plural': '會員'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='publicmassagechair',
            options={'verbose_name': '公共按摩椅', 'verbose_name_plural': '公共按摩椅'},
        ),
        migrations.AlterModelOptions(
            name='publicmassagechairlocation',
            options={'verbose_name': '公共按摩椅服務據點', 'verbose_name_plural': '公共按摩椅服務據點'},
        ),
        migrations.AlterModelOptions(
            name='publicmassagechairusagerecord',
            options={'verbose_name': '公共按摩椅使用紀錄', 'verbose_name_plural': '公共按摩椅使用紀錄'},
        ),
        migrations.AlterModelOptions(
            name='purchaserecord',
            options={'verbose_name': '進貨紀錄', 'verbose_name_plural': '進貨紀錄'},
        ),
        migrations.AlterModelOptions(
            name='revenuerecord',
            options={'verbose_name': '營收紀錄', 'verbose_name_plural': '營收紀錄'},
        ),
        migrations.AlterModelOptions(
            name='salesrecord',
            options={'verbose_name': '銷售紀錄', 'verbose_name_plural': '銷售紀錄'},
        ),
        migrations.AlterModelOptions(
            name='salestechnique',
            options={'verbose_name': '推銷手法', 'verbose_name_plural': '推銷手法'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '店家', 'verbose_name_plural': '店家'},
        ),
        migrations.AlterModelOptions(
            name='storereview',
            options={'verbose_name': '店家評價', 'verbose_name_plural': '店家評價'},
        ),
        migrations.AlterModelOptions(
            name='storesalestarget',
            options={'verbose_name': '店家業績目標', 'verbose_name_plural': '店家業績目標'},
        ),
        migrations.AlterModelOptions(
            name='transactionrecord',
            options={'verbose_name': '推銷紀錄', 'verbose_name_plural': '推銷紀錄'},
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('興趣', '興趣'), ('關注', '關注'), ('購買', '購買')], max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='店家ID'),
        ),
    ]
