# Generated by Django 4.0 on 2023-06-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se_function', '0006_rename_review_id_employeeservicereview_ereview_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_target',
            field=models.IntegerField(null=True),
        ),
    ]
