# Generated by Django 4.0 on 2023-06-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('hire_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('store_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalesTarget',
            fields=[
                ('sales_target_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField()),
                ('target_year', models.IntegerField()),
                ('target_month', models.IntegerField()),
                ('target_amount', models.IntegerField()),
                ('target_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeServiceReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review_content', models.TextField()),
                ('review_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField()),
                ('store_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('store_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicMassageChair',
            fields=[
                ('chair_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('status', models.CharField(choices=[('可使用', '可使用'), ('不可使用', '不可使用')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PublicMassageChairLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField()),
                ('location_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PublicMassageChairUsageRecord',
            fields=[
                ('usage_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('chair_id', models.IntegerField()),
                ('member_id', models.IntegerField()),
                ('usage_date', models.DateField()),
                ('usage_time', models.TimeField()),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('purchase_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('store_id', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('purchase_quantity', models.IntegerField()),
                ('purchase_unit_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RevenueRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField()),
                ('revenue_year', models.IntegerField()),
                ('revenue_month', models.IntegerField()),
                ('revenue_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('sales_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('store_id', models.IntegerField()),
                ('sales_date', models.DateField()),
                ('sales_quantity', models.IntegerField()),
                ('product_unit_price', models.IntegerField()),
                ('warranty_period', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('信用卡', '信用卡'), ('現金', '現金')], max_length=100)),
                ('total_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesTechnique',
            fields=[
                ('sales_technique_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_technique_name', models.CharField(max_length=100)),
                ('sales_technique_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StoreReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField()),
                ('member_id', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review_content', models.TextField()),
                ('review_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreSalesTarget',
            fields=[
                ('sales_target_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField()),
                ('target_year', models.IntegerField()),
                ('target_month', models.IntegerField()),
                ('target_amount', models.IntegerField()),
                ('target_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('sales_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_date', models.DateField()),
                ('member_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('sales_technique_id', models.IntegerField()),
            ],
        ),
    ]
