# Generated by Django 4.0 on 2023-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se_function', '0002_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('銷售', '銷售'), ('經理', '經理')], max_length=100),
        ),
    ]
