# Generated by Django 4.0 on 2023-06-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se_function', '0004_alter_product_category_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicmassagechairusagerecord',
            name='usage_time',
            field=models.IntegerField(),
        ),
    ]
