# Generated by Django 4.0 on 2023-06-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('se_function', '0005_alter_publicmassagechairusagerecord_usage_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeservicereview',
            old_name='review_id',
            new_name='ereview_id',
        ),
        migrations.RenameField(
            model_name='storereview',
            old_name='review_id',
            new_name='sreview_id',
        ),
    ]
